name: Python Daily Automation

on:
  schedule:
    - cron: '0 8 * * *'  # Corre todos los días a las 8:00 UTC
  workflow_dispatch: {}   # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests
        # pip install cualquier otra librería

    - name: Run script
      run: python main.py
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        CALENDAR_API_KEY: ${{ secrets.CALENDAR_API_KEY }}
        TEAMS_FLOW_URL: ${{ secrets.TEAMS_FLOW_URL }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
