name: Scheduled job

on:
  schedule:
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Ejecutar script o comando
        run: echo "Ejecutando a las 10:00 AM de lunes a viernes"
